# Ví dụ Vector & Ma trận (NumPy)

## Vector Examples

In [19]:
import numpy as np

#Khởi tạo vector mảng một chiều
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([[1],[2],[3]]) # Vector cột (ma trận 3x1)

#Cộng hai vector
print("1. Cộng vector:", v1 + v2) #[1+4, 2+5, 3+6]

#Trừ hai vector
print("2. Trừ vector:", v1 - v2) #Tương tự trên nhưng trừ từng phần tử 

#Nhân vô hướng
print("3. Nhân vô hướng:", v1 * 3) #Nhân từng phần tử với một số [1*3, 2*3, 3*3]

#Tích vô hướng
print("4. Dot product:", np.dot(v1, v2)) #1*4 + 2*5 + 3*6 , lưu ý khác: hàm dot có thể tính tích vô hướng hoặc nhân ma trận tùy input

#Tích có hướng
print("5. Cross product:", np.cross(v1, v2))

#Chuyển vị - Đổi cột thành dòng
print("6. Chuyển vị:", v3.T)

#Nhân  từng phần tử 
print("7. Nhân từng phần tử:", v1 * v2) #[1*4, 2*5, 3*6]

#Ghép vector
print("8. Ghép vector:", np.concatenate((v1, v2))) #np.concatenate((array1, array2), axis=...) ghép theo chiều muốn, với vector 1D thì nối đuôi nhau

#Cộng hằng số
print("9. Cộng hằng số:", v1 + 5) #Tương tự, cộng từng phần tử với 5

#Tạo vector ngẫu nhiên
print("10. Vector ngẫu nhiên:", np.random.randint(1, 10, size=5))

1. Cộng vector: [5 7 9]
2. Trừ vector: [-3 -3 -3]
3. Nhân vô hướng: [3 6 9]
4. Dot product: 32
5. Cross product: [-3  6 -3]
6. Chuyển vị: [[1 2 3]]
7. Nhân từng phần tử: [ 4 10 18]
8. Ghép vector: [1 2 3 4 5 6]
9. Cộng hằng số: [6 7 8]
10. Vector ngẫu nhiên: [2 7 4 2 4]


## Matrix Examples

In [ ]:
import numpy as np # Import thư viện NumPy với alias là np

# Khởi tạo Ma trận A (2x2)
A = np.array([[1, 2],
              [3, 4]])

# Khởi tạo Ma trận B (2x2)
B = np.array([[5, 6],
              [7, 8]])

# Cộng ma trận (Element-wise Addition): Cộng từng phần tử tương ứng của A và B
print("Cộng ma trận:\n", A + B)

# Trừ ma trận (Element-wise Subtraction): Trừ từng phần tử tương ứng của A và B
print("Trừ ma trận:\n", A - B)

# Nhân vô hướng (Scalar Multiplication): Nhân mỗi phần tử của A với giá trị vô hướng là 5
print("Nhân vô hướng:\n", A * 5)

# Nhân ma trận (Matrix Multiplication): Tính tích ma trận A và B (A @ B là toán tử cho tích ma trận)
print("A @ B:\n", A @ B)

# Định thức ma trận (Determinant): Tính định thức của ma trận vuông A
print("det(A):", np.linalg.det(A))

# Chuyển vị ma trận (Transpose): Hoán đổi vị trí dòng và cột của A
print("A.T:\n", A.T)

# Nối cột (Concatenation, axis=1): Ghép ma trận A và B theo chiều ngang (cột)
print("Nối cột:\n", np.concatenate((A, B), axis=1))

# Nối dòng (Concatenation, axis=0): Ghép ma trận A và B theo chiều dọc (dòng)
print("Nối dòng:\n", np.concatenate((A, B), axis=0))

# Trích dòng (Row Slicing): Trích xuất toàn bộ các phần tử ở dòng có chỉ số 1 (dòng thứ hai)
print("Trích dòng 1:", A[1, :])

# Trích cột (Column Slicing): Trích xuất toàn bộ các phần tử ở cột có chỉ số 0 (cột thứ nhất)
print("Trích cột 0:", A[:, 0])

# Tạo ma trận random: Tạo ma trận 3x3 chứa các số nguyên ngẫu nhiên trong khoảng [1, 9]
print("Ma trận random 3x3:\n", np.random.randint(1, 10, size=(3, 3)))

# Ma trận nghịch đảo (Inverse Matrix): Tính ma trận nghịch đảo của A (chỉ áp dụng cho ma trận vuông khả nghịch)
print("A^-1:\n", np.linalg.inv(A))

# Hạng ma trận (Matrix Rank): Tính hạng của ma trận A
print("rank(A):", np.linalg.matrix_rank(A))

1. Cộng ma trận:
 [[ 6  8]
 [10 12]]
2. Trừ ma trận:
 [[-4 -4]
 [-4 -4]]
3. Nhân vô hướng:
 [[ 5 10]
 [15 20]]
4. A @ B:
 [[19 22]
 [43 50]]
5. det(A): -2.0000000000000004
6. A.T:
 [[1 3]
 [2 4]]
7. Nối cột:
 [[1 2 5 6]
 [3 4 7 8]]
8. Nối dòng:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
9. Trích dòng 1: [3 4]
10. Trích cột 0: [1 3]
11. Ma trận random 3x3:
 [[3 1 3]
 [6 2 2]
 [8 9 2]]
12. A^-1:
 [[-2.   1. ]
 [ 1.5 -0.5]]
13. rank(A): 2
